kind: Service
apiVersion: v1
metadata:
  name: mssql-ext-db-svc
  namespace: default
spec:
 type: ExternalName
 externalName: 10.0.2.2
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-db-svc
spec:
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mssql-db-svc
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 1433
