version: '3.7'
services:
  pulse-ftp:
    build:
      context: ./docker
      args:
        SSH_MASTER_USER: ${SSH_MASTER_USER}
        SSH_MASTER_PASS: ${SSH_MASTER_PASS}
    hostname: pulse-ftp
    image: pulse-ftp
    container_name: pulse-ftp

    ports:
      - "2222:22"
    volumes:
      - /uploads:/uploads
