version: '3.3'
services:
  infini-cache:
    build: .
    image: infini-cache
    container_name: infini-cache
    #network_mode: "host"
    environment:
      - JAVA_OPTIONS="-Dinfinispan.cors.enableAll=https://host.domain:port"
    ports:
        - "11222:11222"
    entrypoint: ["/opt/infinispan/bin/server.sh", "-Djboss.default.jgroups.stack=kubernetes"]

